### ISSUE TITLE
Premium Promotion-only Contract should not reference course marshals

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#171]
Under "Your Responsibilities" the contract says:
Course Support: Aid stations and Course Marshals at key locations along the route are recommended and are the responsibility of the race organizers.

This really isn't our concern if we're only doing promotion.

**Comment by louking** [comment]
Modified contract listitem, priority 110 to 

`{% if "finishline" in servicenames or "coursemarking" in servicenames %}Course Support: Aid stations and Course Marshals at key locations along the route are recommended and are the responsibility of the race organizers.{% endif %}`

**Comment by louking** [comment]
verified with https://docs.google.com/document/d/13eDt7LUA8MX98wIZdnSVMTwnIZCssFCFZQmFXpqZgoI/view

and 

https://docs.google.com/document/d/16IUZAUPvgcenqWipsPs2rHkYKx8hdhagBSfdzb4SB-8/view
