### ISSUE TITLE
sponsors table: field definition

### ISSUE THREAD

**Issue by louking** [louking/contracts#175]
See bottom for current MSM Sponsor spreadsheet fields. 

This can be reduced to the following, by referencing Client and SponsorLevel tables:

* Race
  * see [race definition](https://github.com/louking/contracts/blob/9beae3d995aac52ff5f83e7efb141116c9c16724/contracts/dbmodel.py#L345)
* Race Year
* Client
  * Company
  * Company Contact
  * [Title] - to be added
  * Address
  * Company URL
  * Email
  * Phone
* State [renewed-pending, tentative, committed]
* Race Contact [was MSM Contact, used by RD to know who contacts sponsor]
* Email Sent [date]
* Level
  * #entries [couponcount]
  * see [level definition](https://github.com/louking/contracts/blob/9beae3d995aac52ff5f83e7efb141116c9c16724/contracts/dbmodel.py#L365) for more fields
* Amount [dollars]
* Date Signed [date set when contract transmitted]
* Invoice Sent [date]
* ~~agreement sent~~ [date, not needed because same as Date Signed]
* ~~Paid~~ [removed]
* Promo Code [admin fills in, code updates RSU]
* Registration Site [RSU] Updated [automated for coupon/promo code, but yes,no for other stuff like logo]
* Website Updated [yes/no]
* Logo Received [yes/no]
* TY on FB [yes/no]
* Notes

Current MSM sponsor spreadsheet has

* Date Signed
* Company
* MSM Contact
* Company Contact
* title
* Address
* Company URL
* Email
* Email Sent
* Phone
* Amount
* Level
* Invoice Sent
* agreement sent
* Paid
* #entries
* Promo Code
* RSU Updated
* Website Updated
* Logo Received
* TY on FB
* Notes

**Comment by hhlanglois** [comment]
- Is there any way for us to attach a logo file?

-Thank You Note sent (either Y/N or date)

- Sometimes there is a secondary contact. Like if the initial inquiry goes to the business owner, but then they want us to deal with an admin.  Not sure how to handle that. Maybe the owner then is just recorded in the notes and the admin becomes the contact.

- I have a field for new, up, down, same to track year to year changes

**Comment by louking** [comment]
I've been thinking about logos as an enhancement, at least for the race. The system would use the race logo in the agreement heading. Are you also talking about sponsor logos? Would you use this as the repository for sponsor logos rather than google drive? The system, I think, doesn't have any use for the sponsor logos.

But even the race logo might not be available on the initial release.

I'll add a **trend** field to track new, up, down, same for tracking year on year changes.

I'll think about secondary contacts, but I think your workaround is probably ok.

**Comment by hhlanglois** [comment]
Yes - I guess I was thinking about using this system as the respository for
sponsor and client race logos. But that would be a "nice to have"
capability and not a real requirement.
