### ISSUE TITLE
Unable to Update and Send Contract

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#207]
![Capture](https://user-images.githubusercontent.com/7198600/55346187-e3be7380-547f-11e9-9fb9-783216811fcc.JPG)

For Friends 10k, 5k, Fun Run and Tot Trot on October 27
Note that I WAS able to change the state to tentative

**Comment by louking** [comment]
I've captured what I need to.

Try logging out / logging in, then doing this again.

**Comment by hhlanglois** [comment]
OK - it went through that time.

**Comment by louking** [comment]
duplicat #208
