### ISSUE TITLE
sponsors: limit sponsors by sponsorlevel.maxallowed

### ISSUE THREAD

**Issue by louking** [louking/contracts#213]
don't show in sponsorshipquery form

any changes to admin.sponsors for this?

**Comment by louking** [comment]
@hhlanglois - I think the current count of a sponsor level should inhibit display of that level in the sponsorship query form (aka signature race sponsorship registration). 

But I am not sure we should prevent an admin/race director from adding a sponsorship which goes beyond the max level.

What do you think?

**Comment by hhlanglois** [comment]
Yes - if the max number of sponsors at a level has been reached, we shouldn't display that level on the sponsor signup for any longer.  I suppose we can allow a race director to add another one manually, but it's hard to see why we would do that. I think it would be bad practice and we could just increase the limit if we were going to do that.

**Comment by louking** [comment]
I think you are saying the following

* you agree that sponsor registration page should not show filled levels (no brainer)
* sponsors page should not allow admin to pick level which is full (some work, but doable -- I was trying 
   to avoid this work)
  * but maybe this isn't required for initial launch?

**Comment by louking** [comment]
In order to determine if the level is filled, code will look for the sponsorships attached to that level. Since the level doesn't have raceyear associated with it, the code will see all the sponsorships for all years. So a filter is required to filter on sponsorships attached to a level for a given raceyear.

Quandry is the following: is it ok to assume current year to filter the sponsorships attached to a level? Or should the code be more clever, e.g., if we had an early race the current year may not be the correct year to filter on.

**Comment by louking** [comment]
Determined best way to determine raceyear filter is to look for latest raceyear for the given sponsorrace.
