### ISSUE TITLE
Sponsorship Level Filter displays more than selected level

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#261]
When I filter on SS8k Platinum, I get Platinum and Platinum-Plus

**Comment by louking** [comment]
need to use `filter_match_mode: 'exact'`

see https://github.com/vedmack/yadcf/blob/f85c058a012262dd186aaecfb6f4a7e9eea7ce13/dist/jquery.dataTables.yadcf.js#L197

**Comment by hhlanglois** [comment]
how do I do that?

**Comment by louking** [comment]
that was a note for me

**Comment by hhlanglois** [comment]
Oh. I thought you were making me read code.
