### ISSUE TITLE
sig races: add race registration year on year charts

### ISSUE THREAD

**Issue by louking** [louking/contracts#264]
* filter on race
* filter on one or more events
* show frequency by day vs. cumulative

anything else @hhlanglois?

- [ ] cumulative filtering (reduce events in pulldown)
- [x] date of year
- [x] days after registration opens
- [x] days until race date
- [x] remove test race from pulldown
- [x] limit display in current year and after race date
- [x] check/limit number of years shown
- [ ] auto fill window with chart
- [ ] frequency by day (week? month?) vs cumulative

**Comment by hhlanglois** [comment]
Looks good. Thanks.

**Comment by louking** [comment]
advanced features moved to #273
