### ISSUE TITLE
sponsorship chart, bad information

### ISSUE THREAD

**Issue by louking** [louking/contracts#300]
As of 1/6/2020, the sponsorship line on the Women's Distance Festival shows $0, with 1/14/20 shown on mouse hover. There have been sponsorships, so it's not clear why $0 is shown. 

The 1/14 display may be related to #299 but it's not clear. 

@hhlanglois

**Comment by hhlanglois** [comment]
there is definitely something wrong with counting the sponsorships that I
booked in 2019.

The Total should be $9,000 as of this week, and it only shows $4,000 in the
01/05 - 01/11 row (although the total at the top is correct).

The dates of each sponsorship are:

11/11/2019: $3,500
11/26/2019: $1,500
1/3/2020: $1,500
1/6/2020: $1,500
1/6/2020: $1,000


[image: image.png]
