### ISSUE TITLE
Modify race contract to indicate that sharing of email list is optional

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#308]
Let's reword the race contract to say: 

If you would like to ensure that we are reaching all of your past participants,  we will add your list of participant emails to our list of contacts. (Just send us a spreadsheet with the list of email addresses).  If you choose to share your email list with us, we suggest that you include a statement in your race waiver as follows: "I understand that I may receive emails about this race and other races promoted by the Frederick Steeplechasers Running Club."  We do not share our contact list with any other organizations and use it only for informing runners of local races.

**Comment by louking** [comment]
Please confirm the following:

I think you are talking about the list item which is displayed only for premium-promotion. I think you want your text prefixed with "Premium Promotion: ". 

This is the old text I see in the database (race services / contract / 100 / listitem)

`{% if "premiumpromotion" in servicenames %}Premium Promotion: We would like to make sure that we are reaching all of your interested participants. Provide spreadsheet file of your participants' email addresses from previous year (if available and not already provided), and then provide the current list at the conclusion of the race. Please include a statement in your race waiver as follows: "I understand that I may receive emails about this race and other races promoted by the Frederick Steeplechasers Running Club."{% endif %}`

**Comment by hhlanglois** [comment]
Yes - that is correct

**Comment by louking** [comment]
Is this ok? Ordering, etc? Also this text sounds like we're talking about past year's email addresses -- is that the intent?

https://docs.google.com/document/d/1NxPKwbrQHsrdLaAuHrqUM6TmsePF1IihSGBED3nkZ8k/view

**Comment by hhlanglois** [comment]
well, we used to ask them to send it twice, which I think is not ever going
to happen. This sort of leaves it up to them when they send it to us. I
think this recommends that they send us "last year's list" before we start
promoting the current year. Frankly, I don't think we're going to get too
many races doing this.

**Comment by louking** [comment]
Updated in production database
