### ISSUE TITLE
Changing race date doesn't update the "days to race" chart to include the later days

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#327]
I noticed that SS8k registrations showed 202 with 0 "days to race" for 2020, when RSU says that there were 212 registrations total.  There were 202 registrations on June 20, the original date of the race. So I changed the race date from June 20 (start of virtual period) to July 4 (end of virtual period). The date chart is correct, but the "days to race" chart is still stuck at 202.

Sorry that this issue has so many 2's and 0'.

**Comment by louking** [comment]
race date currently comes from RunSignUp, using the start_time (and date) for each event

possibly end_time would be a better solution

see https://github.com/louking/contracts/blob/f965bc95feaec2547936bef19a59eec438a6cb7a/contracts/views/admin/racessummary.py#L117

**Comment by louking** [comment]
Looks like maybe last registration_closes date for each event might be the right answer.

```
"registration_periods": [{
                "registration_opens": "6\/22\/2020 00:01",
                "registration_closes": "10\/18\/2020 23:59",
                "race_fee": "$30.00",
                "processing_fee": "$0.00"
            }],
```
