### ISSUE TITLE
events: support add ons

### ISSUE THREAD

**Issue by louking** [louking/contracts#35]
AddOn table

**Comment by louking** [comment]
not needed first day of service

**Comment by louking** [comment]
@hhlanglois 
* should we identify the add-on in the lead email sent 2 days before the race? I think so as I don't think the lead will review the contract
* should we identify the add-on in the email sent to the race director (and lead) 5 days before the race? I think not, other than having it as part of the contract

**Comment by hhlanglois** [comment]
As long as the lead is reminded ahead of the race, I think it's OK. So -
two days notice is sufficient.

**Comment by louking** [comment]
because of addldistance add-on should I change "fun run" start time/distance to "additional" start time/distance in the event entry?

But... there is some use case questions, and also how to inform lead:

* if the admin doesn't set the (main) start time to the earliest time, the lead will be late
* maybe rather than capture addl start/distance instead of fun run, admin should put any information in the notes and the notes should be in the lead email? Not sure what other cases might come up, so maybe this is the best general solution

**Comment by hhlanglois** [comment]
Yes - I think the general solution is best. There may be other specifics
that the lead should be reminded of.

**Comment by louking** [comment]
I'm not planning to put any protective logic in viz. addons. E.g., I'm not planning to verify that if the admin configures addldistance addon, that finishline service has also been configured.
