### ISSUE TITLE
Add csv export to Sponsor Benefit Table

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#440]
The sponsor benefit table is only available to Super Admins, so it would be nice to be able to export the content for a particular race to send to the RD for review.

**Comment by louking** [comment]
should I make this available to RDs? the only issue is that any RD could
change any race's benefits (perhaps accidentally), but that issue exists
for sponsors as well

**Comment by hhlanglois** [comment]
I was thinking it should still only be available to Super Admins. That way I can do the export and send to the RD.
Also, if it's easy, maybe the variable table too.
