### ISSUE TITLE
SS8K registration data shows VIRTUAL One Mile Fun Run/Walk but it's not VIRTUAL

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#444]
The Fun Run/Walk is only in-person and it's configured correctly in RSU (I think).  Where did contractility get VIRTUAL?

**Comment by louking** [comment]
The VIRTUAL One Mile Fun Run/Walk was configured in 2020 and had registrants, so that is why it is showing up in the filter. The One Mile Fun Run/Walk from 2023 doesn't have any registrants yet so that is why it isn't showing up.
