### ISSUE TITLE
"The CSRF tokens do not match" on login failure

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#467]
I am unable to login and get the message "The CSRF Tokens do not match".

**Comment by louking** [comment]
Thoughts

- https://github.com/Flask-Middleware/flask-security/issues/322

**Comment by louking** [comment]
I wonder if this is related to #466? I don't know what led up to this, and I suspect you don't remember either. I'm going to close this and if it recurs after the fix for #466 is deployed, we'll reopen it.
