### ISSUE TITLE
CSV export of sponsorships cuts off Notes column after 19 characters

### ISSUE THREAD

**Issue by hhlanglois** [louking/contracts#468]
Example: no longer supplyingâ€¦
Note three garbage characters at the end

**Comment by louking** [comment]
This may be solvable based on the comment from Tracy Logan at https://datatables.net/plug-ins/dataRender/ellipsis

@hhlanglois how urgent is this?

**Comment by hhlanglois** [comment]
Not urgent. It's just a little inconvenient.
